### ISSUE TITLE
Tag for PHP 5.4

### ISSUE THREAD

**Issue by guilhermednt** [nov/jose-php#35]
This is likely related to #34.

We currently depend on `2.2.0` but only `2.2.1` is available and it requires PHP 5.6. Since we are constrained to using pure RHEL, we only have PHP 5.4 available. Would you tag 2.2.0 (a7fa2b3a02ce62f1edc1804dd93bc81e7cb59f8c) again so we can keep using it until Red Hat, someday, decides it's time to update PHP?

Thanks! :)

**Comment by nov** [comment]
I've just pushed tags which was in my local repository.
2.2.0 also there.

sorry for your inconvenience.
