### ISSUE TITLE
Wrong ENC_KEY calculation for JWE Authorization Tag

### ISSUE THREAD

**Issue by petryla** [nov/jose-php#4]
As stated in the protocol of JWE https://tools.ietf.org/html/draft-ietf-jose-json-web-encryption-40#appendix-B.1 "Use the last X bits of this key as the AES CBC key ENC_KEY". In the deriveEncryptionAndMacKeysCBC function encryption key is calculated skipping first X bits from the secret

**Comment by nov** [comment]
Isn't the last 128 bit of the 256 bit secret same with what calculated skipping first 128 bits from the secret?

**Comment by petryla** [comment]
Its true, but in this case the secret is related to encryption method. If I want to use different encryption method (different sha size) with the same key, it will not work correctly.

**Comment by nov** [comment]
You can't use the same key with different SHA size.
Key length MUST be same with the SHA size.

Read more details about JWA spec.
https://tools.ietf.org/html/rfc7518#section-5.2.3

**Comment by petryla** [comment]
Thats clear. My implementation was incorrect. Thank you.
